version: '3.8'

networks:
  mynetwork:
    driver: bridge
services:
  db_batchid_subsystem:
    build:
      context: .
      dockerfile: Dockerfile.dbatch
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - db
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto:latest # MQTT image Mosquitto
    ports:
      - "1883:1883"  # MQTT port
      - "8883:8883"    # MQTTS (secure)
    networks:
      - mynetwork
    volumes:
    - /mosquitto/data:/mosquitto/data
    - /mosquitto/config:/mosquitto/config
    
    restart: always
  sensor_mqtt:
    container_name: sensor_mqtt
    image: sensor_mqtt
    depends_on:
      - mqtt
    ports:
      - "4500:4500"  # MQTT port
    networks:
      - mynetwork
    build:
      context: .
      dockerfile: Dockerfile.mqtt
    restart: always  
  scheduler:
    image: scheduler
    build:
      context: .
      dockerfile: Dockerfile.JavaScheduler
    ports:
      - "9000:9000"
    networks:
      - mynetwork
    restart: always
  cuttingmachine:
    image: cuttingmachine
    depends_on:
      - mqtt
    build:
      context: .
      dockerfile: Dockerfile.cuttingmachine
    ports:
      - "4000:4000"
    networks:
      - mynetwork
    restart: always
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - mynetwork
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
  

    
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka
    container_name: kafka
    networks:
      - mynetwork
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: LISTENER_INTERNAL://0.0.0.0:29092,LISTENER_EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INTERNAL://kafka:29092,LISTENER_EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_MIN_INSYNC_REPLICAS: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 5
    volumes:
      - kafka-data:/var/lib/kafka/data
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Mount init.sql for initialization 
      - db_data:/var/lib/postgresql  # Named volume for data persistence
  pgadmin:
      image: dpage/pgadmin4:latest
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: pgadmin
        PGADMIN_LISTEN_PORT: 80
      ports:
        - "5000:80"
      depends_on:
        - db
      networks:
        - mynetwork
      volumes:
      - db_data:/var/lib/postgresql  # Named volume for data persistence


volumes:
  db_data:
  zookeeper-data:
  zookeeper-logs:
  kafka-data:
  mosquitto_data:
  mosquitto_config:
  
